### ISSUE TITLE
Point cloud support

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#142]
`pnts` support was recently added to Cesium Native: https://github.com/CesiumGS/cesium-native/pull/591. At some point we should investigate rendering point clouds in Omniverse.

* What is or isn't possible with USD?
* How do we maintain constant pixel size? See @kring's comment in https://github.com/CesiumGS/cesium-unity/issues/201#issuecomment-1418382985. I don't think we can write our own vertex shaders, but Fabric allows you to update GPU vertex data directly: http://omniverse-docs.s3-website-us-east-1.amazonaws.com/usdrt/5.0.0/docs/whatsinfabric.html#deforming-a-mesh-on-the-gpu-with-warp
* How much control do we have over point cloud shading, e.g. would it be possible to implement eye dome lighting? CC https://github.com/CesiumGS/cesium-unity/issues/201

**Comment by corybarr** [comment]
After talking with @lilleyse, we decided to save points and render directly in Fabric and bypass using USD/Flow. Aside from the performance boost of going straight to Fabric, there are a few other potential benefits:

- Control over the type of created geometry (quads initially, but potentially cubes)
- control over attenuation
- potentially using pre-baked metadata, like distances to neighbors help scale point representations

**Comment by lilleyse** [comment]
@corybarr could you open issues for the remaining point clouds tasks and add them as a checklist here? I think it looks something like this, but please add any others that are missing.

* CUDA kernel to generate quads / voxels to avoid slowdown in FabricGeometry
* CUDA kernel for billboarding
* Geometric-error based attenuation, similar to what Cesium for Unity or CesiumJS are doing
* Material support, i.e. ability to show/hide or set color for points in an MDL. Includes making per-point properties like intensity and classification available as primvars.
* Eye dome lighting or some other surface shading technique, depending on what we can do in Omniverse

**Comment by corybarr** [comment]
@lilleyse Sure:

- [ ] https://github.com/CesiumGS/cesium-omniverse/issues/430
- [ ] https://github.com/CesiumGS/cesium-omniverse/issues/431
- [ ] https://github.com/CesiumGS/cesium-omniverse/issues/432
- [ ] https://github.com/CesiumGS/cesium-omniverse/issues/433
- [ ] https://github.com/CesiumGS/cesium-omniverse/issues/434
- [ ] https://github.com/CesiumGS/cesium-omniverse/issues/435
- [ ] https://github.com/CesiumGS/cesium-omniverse/issues/436

**Comment by lilleyse** [comment]
Initial point cloud rendering support was added in https://github.com/CesiumGS/cesium-omniverse/pull/424
