### ISSUE TITLE
Some prims in the tileset can become orphaned when tileset is moved

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#214]
I have observed a few scenarios where moving a dataset can cause prims to become "orphaned" from their tileset.

Eg. they remain in the scene visually, even if the tileset is set to invisible or deleted, or they remain in place when the tileset is moved.

See below, all of those pieces of terrain are now "detached" from the main terrain (which has been deleted from the scene)

![image](https://user-images.githubusercontent.com/123468416/224582753-b96ae4ae-d53a-455b-a658-84e24af21a51.png)

**Comment by lilleyse** [comment]
As a workaround we disabled Fabric geometry streaming, but we should consider re-enabling it when this issue is fixed in a future version of Kit.

**Comment by lilleyse** [comment]
This is working in the most recent Kit pre-release and should ship in the next official release. At that point we can set `geometryStreaming` back to true, if we want.
