### ISSUE TITLE
Markdown in Readme not compatible with Omniverse Extension UI

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#222]
I've noticed the readme has been updated with Markdown for Github, that isn't compatible with the Omniverse Extension UI

![image](https://user-images.githubusercontent.com/123468416/226230499-c8de758f-f1b7-4ddb-92a9-7c8b71b3bb4f.png)

Also, the Readme is now an exact copy of the main repo readme, which is somewhat irrelevant as if the user has managed to get to the point of seeing this Readme inside Omniverse, they've already successfully installed it. 

Let's clarify the exact purpose and user workflows that are relevant to each readme in our standup

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium-omniverse/pull/229
