### ISSUE TITLE
Globe anchoring

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#235]
Add globe anchoring similar to Unreal and Unity. See https://cesium.com/learn/unity/unity-placing-objects/

We should use cesium-native's `CesiumGlobeAnchor` as a starting point. But first we need to update cesium-native: https://github.com/CesiumGS/cesium-omniverse/issues/234

**Comment by weegeekps** [comment]
@lilleyse Let me know if you want me to break this up into smaller chunks, but I'm getting very close to done here and I'm not sure there's much to break up at this point.
