### ISSUE TITLE
OSM buildings do not appear when loaded unless camera is moved

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#249]
Download the Cesium for Omniverse samples and extract them

Open examples/Vancouver/Vancover.usda, don't move the camera position from default

Let the stage load, buildings will not appear

Move the camera, OSM buildings will suddenly appear

**Comment by kring** [comment]
Actual PR with the fix: https://github.com/CesiumGS/cesium-native/pull/582

**Comment by weegeekps** [comment]
@kring We were just discussing this in our stand-up. Shehzan mentioned that Unreal and Unity had this bug as well.

We are currently on v0.21.0 and I'll be updating us to the latest release tomorrow morning.
