### ISSUE TITLE
Additional stage cameras stop loding tiles after movement

### ISSUE THREAD

**Issue by weegeekps** [CesiumGS/cesium-omniverse#258]
Reported by the NVIDIA team:

> The perspective camera works fine, but adding a stage camera that can be keyframed in the sequencer stops loading tiles after some movement.

This is going to need some digging to solve, but the current hypothesis is that we are only paying attention to one camera for updates, rather than whatever the user's selected camera is.

**Comment by lilleyse** [comment]
Also broken for multi-viewport setups


https://user-images.githubusercontent.com/915398/234914853-c3bf1be2-b25c-418b-b947-060a50de00f4.mp4

**Comment by lilleyse** [comment]
Cesium Native supports multiple view states, we just need to fix the plumbing in our extension.

To get the list of viewports use

```
from omni.kit.viewport.window import get_viewport_window_instances
viewports = get_viewport_window_instances()
```

And then get the `viewport_api` attribute to access the projection matrix.
