### ISSUE TITLE
RTX real-time lighting issues with some tilesets

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#282]
Some 3D tilesets are overly dark when rendered with RTX real-time lighting.  This isn't consistent across all datasets, so it appears to be dataset specific.  See below.

Google 3D tiles - render issues with RTX Real-time
![Google_Lighting](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/c813a25c-4eeb-4c92-95eb-f7c2bdf90ae4)

Aerometrex Denver - no issues
![AMX_Lighting](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/e278e2e9-d858-4bd6-8676-32d6b5ebd10a)

Melbourne Photogrammetry - render issues with RTX Real-time
![Melbourne Photogrammetry](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/b3ce7b65-7536-4b43-aaa6-2ea474307b00)

**Comment by lilleyse** [comment]
This also seems to be related to the HDRI lighting rig in cesium-omniverse-samples because the default lighting looks fine.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/915398/eb3af3cd-a77e-4476-afd6-95ab0751a8ce)

**Comment by r-veenstra** [comment]
Interesting.  I'll do some experimentation with some different light types and configuration.

**Comment by r-veenstra** [comment]
@lilleyse the issue is still there, and it appears specific to any HDR on a Dome Light, including the stock stage lighting.

The reason it is less visible on the stock stage is:

1) The stock stage uses a directional light for the sun, which does not appear to be impacted in RTX Real Time
2) The stock HDRI Dome light is just for background/bounce light and is relatively low intensity compared to the other HDRI's, including NVIDIA's stock ones, which have patches of very high sunlight intensity built in.

If I reduce the stock directional lights intensity to zero, and just rely on the stock dome light, you'll see the RTX version is still quite a bit darker.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/648b4e65-fbb3-4f22-9f49-475f1d37bb9a)

My next step will be to check out the differences from a material point of view between datasets that are successful and those that are not.  Given the Photorealistic tiles are designed to be rendered unlit, it would not surprise me if they have some odd stock settings that cause a problem.

**Comment by kring** [comment]
> Given the Photorealistic tiles are designed to be rendered unlit, it would not surprise me if they have some odd stock settings that cause a problem.

The one I know about is that they set the `metallicFactor` in the PBR portion of the glTF material to be 1.0 (fully metallic). Google's tiles look better in Unreal, at least, if you force it to be 0.0 instead.

**Comment by r-veenstra** [comment]
@kring that would certainly make sense.

Confirmed it's material related - when running with disable materials, I get nice shadows in both RTX and Path Tracing, where shadows are barely present in RTX mode with materials

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/a3450b7a-ba73-49e3-94dd-ebb215f9caf6)

**Comment by r-veenstra** [comment]
Okay so it was indeed the metallicFactor and hardcoding it to 0 gives much better results in RTX Real-time.  I'm not sure there is anything that should actually be done to resolve this as we're displaying the data as it is represented, so there is no bug.

Perhaps the only gap is the potential for overriding material settings, similar to the custom material options we have in the other runtimes.  I have opened #297 accordingly and will close this one out.

![capture 2023-05-25 13 08 06](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/16ee5710-1f94-4075-965c-4a9a020094f7)
