### ISSUE TITLE
Make black the default Python formatter in the workspace file

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#291]
With black the default Python formatter in the workspace file, issues that would cause CI to fail should be visible before committing. 

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/4670d1bc-f547-4e54-ba82-4b6d110670a2)

**Comment by lilleyse** [comment]
@corybarr this seems like a good change, could you open a PR for this? Make sure to update both windows and linux workspaces.
