### ISSUE TITLE
Implement autoupdates for Curl certificate

### ISSUE THREAD

**Issue by weegeekps** [CesiumGS/cesium-omniverse#306]
Certificate stores can inconsistently vary from system to system, especially on Linux machines. To remedy this we bundle a copy of the Mozilla CA certificate store with our application. This is currently manually updated but we need to set up a process which will automatically update it as part of the production build artifact generation.

We can get an up to date copy of the Mozilla certificate from: https://curl.se/docs/caextract.html

**Comment by mattelser** [comment]
fixed with #319
