### ISSUE TITLE
Explore how to run tests against the USD stage

### ISSUE THREAD

**Issue by weegeekps** [CesiumGS/cesium-omniverse#310]
We have various needs for doing simple testing against just a USD stage. We need to explore how to do this with Omniverse and then document and share it with the rest of the team.

**Comment by lilleyse** [comment]
Most of the C++ code depends on `Context` so we should start there. The testing framework will need to initialize and manage the `Context` as if it were a Kit application - e.g. calling `onStartup` and `onShutdown`, passing in a USD stage, and updating the frame.

In theory it should be simple for the testing code to create a USD stage and pass it to `Context::setStageId`, but it may be more complicated than that if there's any Omniverse specific behavior we need to replicate. Also we'll need to figure out how to assign a Fabric `StageReaderWriter` to the USD stage.

**Comment by mattelser** [comment]
@lilleyse suggested tests for the usd utils functions [in this PR](https://github.com/CesiumGS/cesium-omniverse/pull/428#discussion_r1296009801_), which could be a good place to start
