### ISSUE TITLE
non-uniform brightness on some tiles

### ISSUE THREAD

**Issue by mattelser** [CesiumGS/cesium-omniverse#334]
Possibly related to #335. I have only seen this on windows and was not able to reproduce on linux. This is just the standard cesium world terrain + bing, interactive renderer, and clipping distance increased 1000x. 
![tileBug](https://github.com/CesiumGS/cesium-omniverse/assets/62680156/4e3a9dbb-eda1-462d-953e-e70416fbcac7)
The tiles remain when I leave the scene alone, so it doesn't seem like a loading issue. They do appear to deload properly when the camera moves, but some of the new tiles may also not match in brightness.

**Comment by j9liu** [comment]
Not sure if this helps, but this looks similar to https://github.com/CesiumGS/cesium-unity/issues/32. The tiles were using different color profiles because of a bug in C# and C++ reinterop.

> If you click on tiles and look at their textures, the darker ones are all shown as "sRGB" while the lighter ones are shown as "UNorm"

**Comment by lilleyse** [comment]
@j9liu hm... it could definitely be sRGB related

 @mattelser could you check if https://github.com/CesiumGS/cesium-omniverse/pull/336 fixes it?

**Comment by mattelser** [comment]
I am unfortunately not able to reproduce the tile inconsistency on the original commit, but for what it's worth it also isn't happening with your fix in place.

**Comment by lilleyse** [comment]
I'm going to close this now that https://github.com/CesiumGS/cesium-omniverse/pull/336 is merged, but if anyone sees dark tiles please reopen.
