### ISSUE TITLE
Reuse materials where possible

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#344]
In general, it's not possible for prims to share materials since material values and texture paths are baked into the material definition, except in limited cases where primvars are used.

However, if materials are truly identical (same PBR values, untextured) we should be able to share the same material. This would mean updating `ObjectPool` so that it does reference counting for active materials and only releases materials once the count reaches zero.

An example where this would be helpful is when loading Cesium World Terrain without imagery.

**Comment by lilleyse** [comment]
This is also relevant for point clouds which are almost always untextured

**Comment by corybarr** [comment]
@lilleyse "However, if materials are truly identical (same PBR values, untextured) we should be able to share the same material." Sounds like this would apply to many point clouds, too. Right?
