### ISSUE TITLE
Performance Experience

### ISSUE THREAD

**Issue by yuzhouzhijia520** [CesiumGS/cesium-omniverse#419]
The top configuration of the laptop still crashes, and the experience is not good

**Comment by lilleyse** [comment]
@yuzhouzhijia520 what are the specs on your laptop? And just to be clear, do you see crashes, bad performance, or both?

**Comment by lilleyse** [comment]
I'm going to close due to inactivity, but check out the latest version and see if performance is better. We've had some improvements since then.
