### ISSUE TITLE
Extension not working in Code 2023.1.1/Kit 105.0.2

### ISSUE THREAD

**Issue by weegeekps** [CesiumGS/cesium-omniverse#422]
Last night, Code 2023.1.1 was released. This uses Kit 105.0.2 and our extension fails to properly load there in Linux due to the removal of cudart libraries. Once this is resolved, as with #420, we still run into issues as the tilesets fail to load with Fabric enabled.

There are also other issues, including the Cesium Window not appearing when Code launches and the reminder to enable fabric not showing up.

**Comment by lilleyse** [comment]
We can close this now that https://github.com/CesiumGS/cesium-omniverse/pull/420 and https://github.com/CesiumGS/cesium-omniverse/pull/423 are merged.

The other issue was that Code 2023.1.1 no longer has a default light in the scene, but if you add a light the tileset is there.
