### ISSUE TITLE
Unhandled exception when creating a tileset for the second time

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#425]
![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/dc76b70a-f7a5-4212-9d37-b85269cd49ef)

To reproduce:

1. Load a tileset
2. Delete the tileset
3. Reload the same tileset

**Comment by lilleyse** [comment]
Interestingly, the crash only happens if the tileset has materials. If you check "Disable Materials" on the Cesium prim and follow the steps it doesn't crash.

**Comment by corybarr** [comment]
I'm also able to reproduce this without creating a new tileset. I've attached a .usd file to reproduce. These steps should trigger the issue. (You probably need to be on the `add-voxel-point-cloud` branch.)

1. Delete the Melbourne_Point_Cloud prim
2. Enable visibility on the Melbourne_Photogrammetry prim
3. The exception should trigger.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/d0308258-61a5-4fa6-be38-dac25f97c2aa)

[melbourne.zip](https://github.com/CesiumGS/cesium-omniverse/files/12352098/melbourne.zip)

**Comment by lilleyse** [comment]
I'm starting to narrow this down some more. If we retain a reference to the deleted prim's path forever it doesn't crash. That means something in Omniverse is referencing the deleted prim's path well after it's been destroyed. It's strange that this is only a problem for materials.

With my hacky fix I no longer see any crashes when repeatedly reloading CWT. I still see crashes with CWT + Bing but that's a different crash related to Hydra and textures. I'm still narrowing in on that one.

**Comment by lilleyse** [comment]
@mattelser pointed out that if if you click "remove all tilesets" in the debugging window and then create the tileset again it'll hang instead of crashing. I can reproduce that.

**Comment by lilleyse** [comment]
Note also the error printed right before the crash:

> 2023-08-17 21:46:51 [358,281ms] [Warning] [omni.usd] Coding Error: in _PossiblyDestroyRep at line 168 of W:\ac88d7d902b57417\USD\pxr\base\tf\token.cpp -- Failed verification: ' repFoundInSet ' -- failed to find token '' in table for destruction

Which corresponds to [this line in USD](https://github.com/PixarAnimationStudios/OpenUSD/blob/10b62439e9242a55101cf8b200f2c7e02420e1b0/pxr/base/tf/token.cpp#L166-L168).

Here's the call stack:

![image (4)](https://github.com/CesiumGS/cesium-omniverse/assets/915398/5337e30a-28b5-437f-be9b-8eef239c109b)
