### ISSUE TITLE
Performance app crashes

### ISSUE THREAD

**Issue by mattelser** [CesiumGS/cesium-omniverse#450]
The performance app may have multiple issues. 
- Currently it crashes before opening, though @lilleyse found a fix for that (PR pending). 
- Once that is in place and the app opens, however, clicking a first location works but then the app crashes when a second location is selected. This may be an extension of #425, though notably still happens after that workaround was merged.

**Comment by lilleyse** [comment]
I don't see the crashes anymore, most likely fixed by https://github.com/CesiumGS/cesium-omniverse/pull/455.

Though sometimes the tilesets don't load at all when switching between locations...

**Comment by mattelser** [comment]
I also don't see crashes anymore. Closing.
