### ISSUE TITLE
Switch to Alma Linux 8 for release builds / Docker

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#464]
CentOS 7 is approaching End of Life and we should switch to a different OS for our release builds. The minimum recommendations we received were

* Ubuntu: Minimum - 20.04
* RHEL: Minimum - 8.8
* Rocky: Minimum - 8

Ubuntu 20.04 uses glibc 2.31 and RHEL 8.8 and Rocky 8 use glibc 2.28. So with should go with one of the latter two for the widest glibc compatibility.

@weegeekps suggested Alma Linux 8 as an alternative to RHEL and Rocky.

We should update the Docker image and GitHub Actions before the October release.

**Comment by mattelser** [comment]
It looks like the only linux flavor that github provides runners for is Ubuntu, so Alma would need to remain on a self-hosted instance.

**Comment by lilleyse** [comment]
@mattelser for CentOS 7 builds we use `ubuntu-latest` and spin up docker from within ubuntu. I imagine we would continue doing the same here.
