### ISSUE TITLE
The Omniverse platform can't load the Cesium extension version 7 or higher

### ISSUE THREAD

**Issue by nzariei** [CesiumGS/cesium-omniverse#467]
Hi, 
I have the latest version of Omniverse installed, and tried all extension versions from the highest one up to version 6, and only version 6 is working for now. 
I would really appreciate if you could tell me how can I use the latest version of Cesium in omniverse. 
If there is any alternative way to have the latest extension run on omniverse, please let me know.
Thank you

**Comment by lilleyse** [comment]
@nzariei we now have a version table in the getting started guide. Hopefully that helps with any future issues:

https://cesium.com/learn/omniverse/omniverse-quickstart/#step-1-add-the-cesium-for-omniverse-extension-to-omniverse-usd-composer
