### ISSUE TITLE
Perform refactoring pass on UsdNotificationHandler

### ISSUE THREAD

**Issue by weegeekps** [CesiumGS/cesium-omniverse#483]
The `UsdNotificationHandler` needs a refactoring pass performed to clean it up a bit and make the code a bit more self documenting. There are two primary issues that need to be resolved, outlined below, but whoever performs this work should use judgement to decide if there are other improvements that could be made.

1. It's probably time to create a container class for `ChangedPrim`s rather than using a pure vector. We have several cases where we are just passing in boilerplate parameters: in particular the `propertyName` parameter is only used by changed prims rather than added or removed prims. Abstracting adding entries to the collection would allow for self-documenting improvements, ergonomic improvements, and simplify where we need to handle logging.
2. We are also creating a fair number of unnecessary temporary objects in our usages of `emplace_back` that we should clean up. [Clang-tidy is flagging these](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-emplace.html) and the reasoning is [outlined best by this article](https://andreasfertig.blog/2023/04/push_back-vs-emplace_back-when-to-use-what/). Effectively the way we're using `emplace_back` right now doesn't fully provide us with all the benefits and is using more cycles than what is necessary.

**Comment by lilleyse** [comment]
For point 2 -- C++20 added support for `emplace_back` for struct member initialization. Once we're able to switch to C++20 we should make that change. This affects a few areas of the code, not just `UsdNotificationHandler`.

E.g. [this code](https://godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:19,positionColumn:2,positionLineNumber:19,selectionStartColumn:2,selectionStartLineNumber:19,startColumn:2,startLineNumber:19),source:'%23include+%3Ciostream%3E%0A%23include+%3Cvector%3E%0A%0Astruct+Prim+%7B%0A++++int+a%3B%0A++++int+b%3B%0A%7D%3B%0A%0Aint+main()+%7B%0A++++std::vector%3CPrim%3E+prims%3B%0A%0A++++//+C%2B%2B17+approach%0A++++prims.emplace_back(Prim%7B30,+40%7D)%3B%0A%0A++++//+C%2B%2B20+approach%0A++++prims.emplace_back(10,+20)%3B%0A%0A++++std::cout+%3C%3C+prims.size()+%3C%3C+std::endl%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:63.284753363228695,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g114,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:cnl,ver:trunk),(name:glm,ver:'0998')),options:'-std%3Dc%2B%2B20+-Wall+-Wunused',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+11.4+(Editor+%231)',t:'0')),k:36.715246636771305,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',m:56.399132321041215,n:'0',o:'',t:'0'),(g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+11.4+(Compiler+%231)',t:'0')),header:(),l:'4',m:43.600867678958785,n:'0',o:'',s:0,t:'0')),l:'3',n:'0',o:'',t:'0')),version:4) compiles in C++20 but not C++17
