### ISSUE TITLE
Orientation and scale incorrect when using anchor_xform_at_path

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#539]
I'm experiencing an error when trying to use the `anchor_xform_at_path `python function.

It appears to be another race condition (or the same one previously experienced?)

It only occurs when I supply the latitude, longitude and height to the anchor_xform_at_path function, or if I create an anchor and immediately set the lat/lon/height.

If I await `omni.kit.app.get_app().next_update_async()` between creation of the anchor (with no coordinate parameters) and setting lat/lon/height attributes, orientation and scale is as expected.

https://github.com/CesiumGS/cesium-omniverse/assets/123468416/b6d96937-d5b0-4408-9282-c90dcb0c82ad

Script used in the video above.  Work well if you open 00_quickstart.usda from the samples repo.

I've also reproduced this without using payloads and just regular mesh prims like cylinders.

```
import omni.kit.commands
import omni.usd
from pxr import Sdf, UsdGeom, Usd
from cesium.omniverse.api.globe_anchor import anchor_xform_at_path
from asyncio import ensure_future

trees = [
	{"name":"tree_01","latitude":37.7913, "longitude":-122.39032,"height":-28.88791},
]

context = omni.usd.get_context()
stage = context.get_stage()

async def add_trees():
	for t in trees:
	
		anchor_prim_path = "/World/"+t["name"]+"_anchor"
		payload_prim_path = anchor_prim_path+"/"+t["name"]

		anchor_prim: Usd.Prim = UsdGeom.Xform.Define(stage, Sdf.Path(anchor_prim_path)).GetPrim()
		payload_prim: Usd.Prim = UsdGeom.Xform.Define(stage, Sdf.Path(payload_prim_path)).GetPrim()
		omni.kit.commands.execute("AddPayload",
			stage=stage,
			prim_path = payload_prim_path,
			payload=Sdf.Payload(
				assetPath = "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Vegetation/Plant_Tropical/Cuban_Royal_Palm.usd",
				primPath = Sdf.Path.emptyPath
			)
		)

#		Test1: Try to place an anchor on the prim, while setting the lat/lon/height
		anchor_xform_at_path(anchor_prim_path, t["latitude"], t["longitude"], t["height"])

#		Test2: Try to just place the anchor, then set the coordinates
#		anchor_xform_at_path(anchor_prim_path)		
#		anchor_prim.GetAttribute("cesium:anchor:geographicCoordinates").Set(
#			(t["latitude"], t["longitude"], t["height"])
#		)

#		Test3: Place the anchor, wait a frame, then set the coordinates - works!
#		anchor_xform_at_path(anchor_prim_path)		
#		await omni.kit.app.get_app().next_update_async()
#		anchor_prim.GetAttribute("cesium:anchor:geographicCoordinates").Set(
#			(t["latitude"], t["longitude"], t["height"])
#		)

ensure_future(add_trees())
```

**Comment by lilleyse** [comment]
After https://github.com/CesiumGS/cesium-omniverse/pull/626 is merged this should be fixed. Updated code below:

```python
import omni.kit.commands
import omni.usd
from pxr import Sdf, UsdGeom, Usd
from cesium.usd.plugins.CesiumUsdSchemas import (
    GlobeAnchorAPI as CesiumGlobeAnchorAPI
)

CESIUM_GEOREFERENCE_PRIM_PATH = "/CesiumGeoreference"

trees = [
    {"name":"tree_01","latitude":37.7913, "longitude":-122.39032,"height":-28.88791},
]

context = omni.usd.get_context()
stage = context.get_stage()

for t in trees:
    anchor_prim_path = "/World/"+t["name"]+"_anchor"
    payload_prim_path = anchor_prim_path+"/"+t["name"]

    anchor_prim: Usd.Prim = UsdGeom.Xform.Define(stage, Sdf.Path(anchor_prim_path)).GetPrim()
    payload_prim: Usd.Prim = UsdGeom.Xform.Define(stage, Sdf.Path(payload_prim_path)).GetPrim()
    omni.kit.commands.execute("AddPayload",
        stage=stage,
        prim_path = payload_prim_path,
        payload=Sdf.Payload(
            assetPath = "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Vegetation/Plant_Tropical/Cuban_Royal_Palm.usd",
            primPath = Sdf.Path.emptyPath
        )
    )

    globe_anchor = CesiumGlobeAnchorAPI.Apply(anchor_prim)
    globe_anchor.GetGeoreferenceBindingRel().AddTarget(CESIUM_GEOREFERENCE_PRIM_PATH)
    globe_anchor.GetGeographicCoordinateAttr().Set((t["latitude"], t["longitude"], t["height"]))
```

I'm not sure why the tree comes in rotated. It seems like an up axis problem but I'm not sure if it's the asset or something in our code that needs to be fixed.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/915398/45e084de-d841-41b4-aeb4-7485a786d5ae)

**Comment by lilleyse** [comment]
@weegeekps pointed out that our stage is y-up and the payload is z-up. It seems like the fix is to apply a rotation to the tree. 🤷‍♂️

**Comment by r-veenstra** [comment]
@lilleyse it appears OV applies some additional transforms to objects when dragging them in from the NVIDIA Asset library, to account for mismatch in up-axis and also scale.

Dragging a tree into my Y up stage results in this additional transform
![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/2cc47ce1-73e9-44ae-8f2a-0a7921fa8a6e)

Dragging same tree into a Z up stage results in no additional transform

Dragging same tree into a Z up stage with meters as the default unit results in this additional transform
![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/7e451cea-dd02-4727-a789-74cf760fa989)

I assume the globe anchor API is removing these additional transforms?  What happens if you spawn the tree using the script above, but comment out the globe anchor?  It should appear at 0,0,0 with the correct orientation

**Comment by lilleyse** [comment]
> I assume the globe anchor API is removing these additional transforms? What happens if you spawn the tree using the script above, but comment out the globe anchor? It should appear at 0,0,0 with the correct orientation

I get incorrect orientation still. The extra attributes don't get added.

I've been testing this in the dev app instead of USD Composer, if that matters.

**Comment by r-veenstra** [comment]
@lilleyse this must be specific to USD Composer and one of its extensions, as I can confirm like yourself, I do not get the additional transforms added when executing the same code in the dev app.  I'm not 100% sure which extension(s) are required to enable this, I've tried enabling a few asset and payload related ones without any luck

**Comment by lilleyse** [comment]
I pushed a change in https://github.com/CesiumGS/cesium-omniverse/pull/626 so that globe anchors no longer need to explicitly bind to a georeference. If there's no georeference bound it'll use the first georeference (if it exists). This is similar to Cesium for Unreal.

So this line has been removed:

```
globe_anchor.GetGeoreferenceBindingRel().AddTarget(CESIUM_GEOREFERENCE_PRIM_PATH)
```

**Comment by r-veenstra** [comment]
It looks like the API schema has changed slightly since the tree placement script was updated in the earlier comments

To access the lat/lon/height values, the following should be used:

```
globe_anchor.GetAnchorLatitudeAttr().Set(value)
globe_anchor.GetAnchorLongitudeAttr().Set(value)
globe_anchor.GetAnchorHeightAttr().Set(value)
```

**Comment by lilleyse** [comment]
Thanks @r-veenstra, I update the snippet
