### ISSUE TITLE
Adding a Globe Anchor to a scaled prim changes size or position in the stage

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#584]
To reproduce:

1. Create a prim. Do not alter the scale. Add a globe anchor. He prim remains unaltered.
2. Create another prim. Alter the scale and /or translation. Add a globe anchor. The scale and/or translation will change depending on the prim's pre-anchored transformations.

It's possible to avoid the issue, but the user has to set the translation first, add the globe anchor, then update the scale.

**Comment by lilleyse** [comment]
I confirmed that this is fixed in https://github.com/CesiumGS/cesium-omniverse/pull/626.

Existing transforms are unaltered when the globe anchor is added, and you can safely update them afterwards.
