### ISSUE TITLE
Make "Alpha" parameter for a CesiumImageryPrim a constrained slider

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#587]
Currently we have this in the UI:

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/94f20a11-b24e-4018-823d-f492fb9813cb)

Customer styling would be easier if it used a constrained slider like Node Graph UI:

https://github.com/CesiumGS/cesium-omniverse/assets/1040194/66c1d6ee-7ffd-46fe-8526-982680dd7d9f

This is just an attribute above the variable in C#, so might also be in Omniverse/MDL.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium-omniverse/pull/649
