### ISSUE TITLE
Excessive property warnings when using custom material and property lookups

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#588]
Using a custom material to access data in property tables triggers excessive warnings when using property heavy datasets such as Cesium OSM Buildings.

Loading the below usda produces approximately 75,000 warnings.

[osm_buildings_with_properties.zip](https://github.com/CesiumGS/cesium-omniverse/files/13670945/osm_buildings_with_properties.zip)

It may be better to only display warnings for properties that the material is trying to use, as opposed to every property in the tileset.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/0e14834d-5fee-4f1a-8179-8326f29a940a)

**Comment by lilleyse** [comment]
Yup, I'd like to fix this soon. https://github.com/CesiumGS/cesium-omniverse/pull/579 was the first step, but I have a better fix in mind that I haven't gotten to yet.

**Comment by r-veenstra** [comment]
I still seem to be getting this, loading https://github.com/CesiumGS/cesium-omniverse-samples/blob/main/tutorials/07_style_by_properties/07_style_by_properties.usda when running a build of 1d4f98be7001c044a8d4b39759f50895e40a6738 which should have the latest #626 codebase

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/0abec784-e774-435f-9ee6-7653cb949ac3)
