### ISSUE TITLE
USD Composer 2023.2.2 - tiles occasionally load with a shiny gray material

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#602]
With the new release of USD Composer 2023.2.2, it appears that tiles will load in occasionally without a complete material, as per the image below.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/607a6080-705b-4d96-bf73-d2cf147111be)

The below USDA can reliably reproduce this on my workstation with Cesium for Omniverse 0.15.0.

Open the USDA and press play to start a camera flythough.  You should observe tiles with incomplete materials

[flythrough_missing_materials.zip](https://github.com/CesiumGS/cesium-omniverse/files/13757023/flythrough_missing_materials.zip)

**Comment by lilleyse** [comment]
This seems to be fixed in USD Composer 203.2.3.

For local development it should be fixed once kit-sdk `105.1.2+release.137496.fc5a6c6b.tc` is published to packman.

**Comment by r-veenstra** [comment]
I performed some testing yesterday and could not get this issue to reproduce in 2023.2.3 with Cesium for Omniverse 0.16.0 and 0.17.0
