### ISSUE TITLE
Enhance UI/UX for raster overlays

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#618]
This entails the following:

- Make the UI have feature parity with Cesium for Unreal
- Add custom UI widgets for each raster-overlay type
- Make sure the dialog window is filtering the list of prims properly by type when selecting a `rel`
- Appropriate interfaces for the values where possible
  - e.g., a slider bounded to [0,1] for alpha values

**Comment by lilleyse** [comment]
> Add custom UI widgets for each raster-overlay type

Under this I would add making the `CesiumPolygonImagery` -> `CesiumCartographicPolygon` rel accessible in the UI as was recently done for the other prim types.
