### ISSUE TITLE
Do not download tiles if they are fully contained in a CesiumCartographicPolygon

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#619]
This functionality is provided by Cesium Native and is already implemented in Cesium for Unreal.

We should not merge the associated branch until https://github.com/CesiumGS/cesium-native/issues/803 is resolved. It will remove all geo from the inverted clip image in the [Cesium for Omniverse: Tileset Clipping](https://cesium.com/learn/omniverse/omniverse-tileset-clipping/) document.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium-omniverse/pull/658
