### ISSUE TITLE
Cartographic Polygon and Polygon Imagery layer default values

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#631]
I suggest we implement the following default values to make using cartographic polygons and polygon overlays a little easier

Imagery Overlay
- [x] `Overlay Render Method - clipping` - same as Unreal, also less confusing as it won't immediately make the tileset black

Cartographic Polygons - defaults when creating by any method
- [x] `point3f[] points = [(-1000, 0, -1000), (-1000, 0, 1000), (1000, 0, 1000), (1000, 0, -1000)]` - Helpful to have some pre-existing points for the user to grab and edit, vs trying to draw from scratch.  Unreal does this. (especially as raycasting to tilesets is not currently available)
- [x] `uniform token type = "linear"` - Helpful to avoid accidental use of curves which aren't supported
- [x] `uniform token wrap = "periodic"` - Ensures the polygon is closed

cc @corybarr

**Comment by corybarr** [comment]
Setting `point3f[] points = [(-1000, 0, -1000), (-1000, 0, 1000), (1000, 0, 1000), (1000, 0, -1000)]` in the USD schema leads to a crash in Omniverse when a `CesiumCartographicPolygonPrim` is created. I'm seeing if this is solvable, but it might have to be done at the Python level during prim creation.

**Comment by lilleyse** [comment]
@corybarr does that crash happen in https://github.com/CesiumGS/cesium-omniverse/pull/626?

**Comment by corybarr** [comment]
> * `point3f[] points = [(-1000, 0, -1000), (-1000, 0, 1000), (1000, 0, 1000), (1000, 0, -1000)]` - Helpful to have some pre-existing points for the user to grab and edit, vs trying to draw from scratch.  Unreal does this. (especially as raycasting to tilesets is not currently available)
>         
>       
>   
>       Create an issue with the title `point3f[] points = [(-1000, 0, -1000), (-1000, 0, 1000), (1000, 0, 1000), (1000, 0, -1000)]` - Helpful to have some pre-existing points for the user to grab and edit, vs trying to draw from scratch.  Unreal does this. (especially as raycasting to tilesets is not currently available). Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  `uniform token type = "linear"` - Helpful to avoid accidental use of curves which aren't supported
>         
>       
>   
>       Create an issue with the title `uniform token type = "linear"` - Helpful to avoid accidental use of curves which aren't supported. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  `uniform token wrap = "periodic"` - Ensures the polygon is closed

@lilleyse It does happen in #626. The crash's trace doesn't go through our code.

**Comment by corybarr** [comment]
> Setting `point3f[] points = [(-1000, 0, -1000), (-1000, 0, 1000), (1000, 0, 1000), (1000, 0, -1000)]` in the USD schema leads to a crash in Omniverse when a `CesiumCartographicPolygonPrim` is created. I'm seeing if this is solvable, but it might have to be done at the Python level during prim creation.

Since some attributes require setting other attributes, I tried adding `curveVertexCounts` and `extent`. I still got the crash. Given that, I copied all attributes from a working `CesiumCartographicPolygonPrim` but still get the instantiation-time crash.
