### ISSUE TITLE
Cartographic Polygon editing crash - fabric only

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#632]
1. Start USD Composer (I used 2023.2.1) - build from commit d1b7ebcbdcd0020fca64eb21cc8a19ed3abe6a9d
2. Enable fabric
3. Add a Cartographic Polygon via the quick add menu
4. Select it
5. Click Edit Control Vertices
6. Click on the default ground plane to place a first point
7. OV should briefly hang then crash

Note: Does not crash when fabric disabled

cc @corybarr

**Comment by lilleyse** [comment]
This doesn't seem to happen for regular `BasisCurves`.

Maybe a reason for `CesiumCartographicPolygon` to have a `rel` to a `BasisCurves` prim instead of being a subclass.

**Comment by lilleyse** [comment]
Actually, it seems like both `BasicCurvers` or `CesiumCartographicPolygon` are working in USD Composer 2023.2.2.

Still might be worth considering the `rel` approach if that improves the workflow or fixes other bugs.

CC https://github.com/CesiumGS/cesium-omniverse/pull/630 and https://github.com/CesiumGS/cesium-omniverse/issues/636

**Comment by corybarr** [comment]
> This doesn't seem to happen for regular `BasisCurves`.
> 
> Maybe a reason for `CesiumCartographicPolygon` to have a `rel` to a `BasisCurves` prim instead of being a subclass.

Moving to a `rel` would also let us query any prim that has a `points` attr. I can image some hypothetical dataviz workflows where creating a `BasisCurves` would be more work than needed. User wouldn't even necessarily have to even know about a `BasisCurves`.

**Comment by r-veenstra** [comment]
Editing with Fabric enabled in 2023.2.2 does crash

**Comment by r-veenstra** [comment]
@corybarr @lilleyse I can confirm that the original repro steps from this issue no longer cause a crash in 2023.2.2 with latest main 57fdeeebf7c47ed08282d981056be98eb72c49cb

**Comment by r-veenstra** [comment]
However, if I run the repro steps, save a USDA, and re-open the usda, I **do** get a crash

So it seems the issue is currently related to editing CesiumCartographicPolygons that have been loaded from a USDA, vs being freshly created.

**Comment by corybarr** [comment]
That's puzzling. It's strong evidence that we won't be able to fix the issue in our codebase, but let me see if I can did up any more precise info in some tests.

**Comment by corybarr** [comment]
I tested this with the absolute minimal inheritance example:

```
class CesiumBasisCurvesChildPrim "CesiumBasisCurvesChildPrim" (
    doc = """Test prim for inheritance crashes"""
    inherits = </BasisCurves>
    customData = {
        string className = "BasisCurvesChild"
    }
) {
}
```
With a raw `BasisCurves` I was able to create this with FSD enabled:

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/a9d9eb47-daae-4150-82a9-40bfc1debe5b)


With a `BasisCurvesChild` it crashed. Aside from executing the prim's Define via our UI, the example bypasses our codebase. I think we should provide this minimal example to NVIDIA so they can reproduce.

**Comment by corybarr** [comment]
In the meantime, let's fall back to a `rel`. Agreed? @lilleyse @r-veenstra

**Comment by r-veenstra** [comment]
A `rel` that points to a `BasisCurve` with a `GlobeAnchor` added, yes?

**Comment by corybarr** [comment]
@r-veenstra Exactly

**Comment by r-veenstra** [comment]
@corybarr makes sense.  It should also resolve https://github.com/CesiumGS/cesium-omniverse/issues/636
