### ISSUE TITLE
Invert option for polygon raster overlays

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#633]
Add support for inverting the polygon raster overlay as per Cesium for Unreal.  Make clipping exclude outside of the polygon instead of inside.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/dbc07493-467a-4100-8ef4-59588655d3e3)

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/d3ad773f-b17b-4658-9430-ceabe243a72c)

cc @corybarr

**Comment by corybarr** [comment]
Removing the inherited `CesiumCartographicPolygon` prim makes this challenging. With the prim, we can easily add a corresponding property to the schema, which I believe is the proper way to do this. We _can_ create the invert attribute during instantiation at the Python level. However, this has disadvantages:

- There's no guarantee that the prim will have the attribute.
- It doesn't play nice with UI widgets. The raw name of the attribute will be the display name, and the attribute will only appear in the Raw USD Properties:


![Image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/48249166-0a90-4eb3-a573-587cac075ea6)

**Comment by r-veenstra** [comment]
@corybarr doesn't this just live on the `CesiumPolygonRasterOverlay` prim schema, which should still exist?  In Unreal its a property of the overlay, as opposed to individual polygons.

**Comment by corybarr** [comment]
> @corybarr doesn't this just live on the `CesiumPolygonRasterOverlay` prim schema, which should still exist? In Unreal its a property of the overlay, as opposed to individual polygons.

@r-veenstra Yeah, you're right. I just came back here to add that. Seems I worked a bit too much today.
