### ISSUE TITLE
Dragging a CesiumCartographicPolygonPrim in the Stage Window crashes app

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#636]
(Confirmed issue in both `main` and #626.)

To reproduce:

1. Open the attached .usda file.
2. Create a `Scope`
3. Drag one of the `CesiumCartographicPolygonPrims` into the `Scope`:

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/97fc3ce4-fa8a-4be7-81be-0f8f486d3577)

[clippingTest.twoPolygonLayers.usda.zip](https://github.com/CesiumGS/cesium-omniverse/files/14068365/clippingTest.twoPolygonLayers.usda.zip)

**Comment by lilleyse** [comment]
Here's a .usda with globe anchor schema changes needed for testing with https://github.com/CesiumGS/cesium-omniverse/pull/626

[clippingTest.twoPolygonLayers.usda.zip](https://github.com/CesiumGS/cesium-omniverse/files/14069109/clippingTest.twoPolygonLayers.usda.zip)

**Comment by lilleyse** [comment]
The stack trace doesn't seem to be in our code. I wonder if it has to do with Fabric and Basis Curves.

**Comment by corybarr** [comment]
> The stack trace doesn't seem to be in our code. I wonder if it has to do with Fabric and Basis Curves.

That's what I think. I think we should ship with this, then let NVIDIA know once they can reproduce it.

**Comment by corybarr** [comment]
> The stack trace doesn't seem to be in our code. I wonder if it has to do with Fabric and Basis Curves.

Also, there's no crash with the Fabric Scene Delegate disabled.

**Comment by lilleyse** [comment]
A regular `BasisCurves` doesn't crash when moved

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium-omniverse/pull/648
