### ISSUE TITLE
Issue with CesiumGltf/SamplerUtility.h when generative stubs on Windows

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#651]
This doesn't seem to have any impact on development, but still shouldn't be happening.

To reproduce, run `genStubs.bat`.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/7741a89b-d8d7-4849-b43f-13d7b7966edd)

**Comment by lilleyse** [comment]
@corybarr you may need to delete the build folder and rerun. CMake isn't picking up the new cesium-native header for some reason.

**Comment by r-veenstra** [comment]
Yes I can confirm I needed to delete the build and start fresh
