### ISSUE TITLE
Is cesium.usd.plugins still needed as a separate extension?

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#659]
With the ability to install via the Omniverse extension manager, it's somewhat cumbersome for users to make sure they have the correct version of `cesium.usd.plugins` installed alongside `cesium.omniverse`.  Extension manager does not currently support automatically installing the correct version of a depedency that we are aware of.

This begs the quesiton - do we actually need cesium.usd.plugins to be a separate extension?  It would be great if it could be combined from a UX point of view.

**Comment by lilleyse** [comment]
After an attempt to fix this, it doesn't seem like this is technically possible. See notes in https://github.com/CesiumGS/cesium-omniverse/pull/685/#issuecomment-1943944367.
