### ISSUE TITLE
Globe anchors aren't working with payloads using a resolve transform

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#660]
I was updating the Globe Anchors tutorial and noticed Globe Anchors are not functioning correctly with Payloads, when adding the payload results in additional resolve transforms, such as these.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/8e75ecc3-3aec-47db-be90-48e2cbd16940)

Reproduction steps:

- Open USD Composer, load a stage with a tileset.  Ensure stage is Y-up
- From NVIDIA Assets, drag an asset such as a tree onto the terrain (this creates a payload to a remote asset, it should have a 90 degree unit resolve transform on it)
- Right click `Add > Cesium > Globe Anchor`
- The Globe Anchor properties appear on the prim, however the lat/lon/height is 0,0,0

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/842d51fb-d404-408b-b83c-e667822a863f)

- The object doesn't remain on the correct location on the globe if the `CesiumGeoreference` is moved.
- Editing any of the lat/lon/height or ECEF positions doesn't change position of the object
- Globe anchor still doesn't work after a save then reload
- Delete the resolve transforms and the globe anchor works fine
- Globe anchors work fine on regular prims

**Comment by lilleyse** [comment]
> - The Globe Anchor properties appear on the prim, however the lat/lon/height is 0,0,0
> - The object doesn't remain on the correct location on the globe if the `CesiumGeoreference` is moved.
> - Editing any of the lat/lon/height or ECEF positions doesn't change position of the object
> - Globe anchor still doesn't work after a save then reload

If you see any of these, it's because the globe anchor is disabled, and a warning should have showed up in the console.

> 2024-02-01 14:22:34  [Warning] [cesium.omniverse.plugin] [2024-02-01 09:22:34.693] [cesium-omniverse] [warning] Globe anchor xform op order must [translate, rotate, scale] without additional transforms.

I open a PR so that globe anchors work with additional transforms: https://github.com/CesiumGS/cesium-omniverse/pull/662
