### ISSUE TITLE
Extend video-capture tools to render each frame after all 3D Tiles have loaded

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#669]
The feasibility of this needs to be determined.

@timoore mentioned `updateViewOffline()` from Native could likely be used.

This functionality would allow user to create pitch-worthy videos that render without seeing artifacts of tiles loading.

Related techniques could be used as an alternative implementation to https://github.com/CesiumGS/cesium-omniverse/pull/668

**Comment by lilleyse** [comment]
Duplicate with https://github.com/CesiumGS/cesium-omniverse/issues/198?

**Comment by corybarr** [comment]
> Duplicate with #198?

Ah, it is dupe, nearly exact down to the notes.

**Comment by corybarr** [comment]
duplicate

**Comment by corybarr** [comment]
duplicate
