### ISSUE TITLE
Add settings for screen-space error, max texture size, etc to raster overlays

### ISSUE THREAD

**Issue by corybarr** [CesiumGS/cesium-omniverse#675]
Unreal currently exposes additional options for controlling raster overlays that aren't exposed in Omniverse:

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/76a555d2-4544-4cd7-ad02-848fa348da63)

Some of these settings (including max SSE, max tile downloads) are on the tile-set level in Omniverse. Proposal: match Unreal's approach by moving these settings from the tileset and adding the additional ones.

**Comment by lilleyse** [comment]
> Some of these settings (including max SSE, max tile downloads) are on the tile-set level in Omniverse. Proposal: match Unreal's approach by moving these settings from the tileset and adding the additional ones.

These options are at both the tileset and raster overlay level in Unreal. So they don't need to be moved over, just added to raster overlays.
